<a href="https://colab.research.google.com/github/25wh1a0536-lgtm/Nasscom/blob/main/week-2/U5_Calculus_for_ML_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import sympy as sp

x, y = sp.symbols('x y')
sp.init_printing()
np.random.seed(42)
print('Setup complete. SymPy', sp.__version__, '| NumPy', np.__version__)


Setup complete. SymPy 1.14.0 | NumPy 2.1.3


In [2]:
def f(x):
    return x**2

h = 1e-6
slope_at_3 = (f(3 + h) - f(3)) / h
print('Numerical f\'(3):', round(slope_at_3, 4), ' (exact = 6)')

expr = x**2
deriv = sp.diff(expr, x)
print('d/dx (x**2) =', deriv)     # 2*x

# Evaluate the symbolic derivative at x = 3
print('Symbolic f\'(3) =', deriv.subs(x, 3))


Numerical f'(3): 6.0  (exact = 6)
d/dx (x**2) = 2*x
Symbolic f'(3) = 6


In [3]:
def g(x):
    return x**3 + 2*x

# 1. Numerical derivative at x = 2 (use h = 1e-6)
h = 1e-6
slope_at_2 = (f(2 + h) - f(2)) / h
print('Numerical f\'(3):', round(slope_at_3, 4), ' (exact = 6)')

# 2. Symbolic derivative of x**3 + 2*x
expr = x**3 + 2*x
deriv = sp.diff(expr, x)
print('d/dx (x**3 + 2*x) =', deriv)

# 3. Evaluate the symbolic derivative at x = 2 and compare
print('Symbolic f\'(2) =', deriv.subs(x, 2))

Numerical f'(3): 6.0  (exact = 6)
d/dx (x**3 + 2*x) = 3*x**2 + 2
Symbolic f'(2) = 14


In [4]:
f2 = x**2 + 3*x*y + y**2

# A partial derivative differentiates ONE variable, holding others fixed
print('df/dx =', sp.diff(f2, x))
print('df/dy =', sp.diff(f2, y))
grad = [sp.diff(f2, v) for v in (x, y)]
print('grad f =', grad)

# Evaluate the gradient at the point (x=1, y=2)
grad_at = [g.subs({x: 1, y: 2}) for g in grad]
print('grad f at (1, 2) =', grad_at)


df/dx = 2*x + 3*y
df/dy = 3*x + 2*y
grad f = [2*x + 3*y, 3*x + 2*y]
grad f at (1, 2) = [8, 7]


In [5]:
h2 = x**2 * y + sp.sin(y)

# 1. dh/dx and dh/dy
print('dh/dx =', sp.diff(h2, x))
print('dh/dy =', sp.diff(h2, y))

# 2. Assemble the gradient list
grad = [sp.diff(h2, v) for v in (x, y)]
print('grad h =', grad)

# 3. Evaluate at (x=2, y=0)  -> hint: .subs({x: 2, y: 0})
grad_at = [g.subs({x: 2, y: 0}) for g in grad]
print('grad h at (2, 0) =', grad_at)

dh/dx = 2*x*y
dh/dy = x**2 + cos(y)
grad h = [2*x*y, x**2 + cos(y)]
grad h at (2, 0) = [0, 5]


In [6]:
by_hand = sp.cos(x**2) * 2*x
by_sympy = sp.diff(sp.sin(x**2), x)

print('By hand :', by_hand)
print('By SymPy:', by_sympy)
print('Match?  ', sp.simplify(by_hand - by_sympy) == 0)
expr3 = (3*x + 1)**4
print('d/dx (3x+1)^4 =', sp.diff(expr3, x))   # 12*(3x+1)^3



By hand : 2*x*cos(x**2)
By SymPy: 2*x*cos(x**2)
Match?   True
d/dx (3x+1)^4 = 12*(3*x + 1)**3


In [7]:
# y = exp(x**2 + 1);  inner = x**2 + 1, inner' = 2x, outer' = exp(inner)

# 1. By hand (as a SymPy expression)
x= sp.symbols('x')
y = sp.exp(x**2 + 1)
by_hand = sp.exp(x**2 + 1)*(2*x)
by_sympy = sp.diff(y,x)
print('By hand',by_hand)
print('By sympy',by_sympy)


By hand 2*x*exp(x**2 + 1)
By sympy 2*x*exp(x**2 + 1)


In [8]:
X = np.random.randn(4, 3)
Y = np.random.randn(4, 1)
W1 = np.random.randn(3, 5) * 0.1
W2 = np.random.randn(5, 1) * 0.1

z1 = X @ W1
h  = np.maximum(0, z1)
y_hat = h @ W2
loss = ((y_hat - Y) ** 2).mean()
print('Initial loss:', round(loss, 4))


Initial loss: 1.6936


In [9]:
dy   = 2 * (y_hat - Y) / Y.size
dW2  = h.T @ dy
dh   = dy @ W2.T
dz1  = dh * (z1 > 0)
dW1  = X.T @ dz1

print('dW1 shape:', dW1.shape, '(matches W1)')
print('dW2 shape:', dW2.shape, '(matches W2)')


dW1 shape: (3, 5) (matches W1)
dW2 shape: (5, 1) (matches W2)


In [10]:
lr = 0.1
W1 -= lr * dW1
W2 -= lr * dW2

# Recompute the loss after the update
h_new = np.maximum(0, X @ W1)
loss_new = ((h_new @ W2 - Y) ** 2).mean()
print('Loss before:', round(loss, 4))
print('Loss after :', round(loss_new, 4), '-> should be lower')


Loss before: 1.6936
Loss after : 1.6524 -> should be lower


In [11]:
Xb = np.random.randn(6, 4)
Yb = np.random.randn(6, 1)
Wa = np.random.randn(4, 8) * 0.1
Wb = np.random.randn(8, 1) * 0.1

import numpy as np
x = np.array([[1.0, 2.0]])
y = np.array([[1.0]])

W1 = np.array([[0.1, 0.2],
               [0.3, 0.4]])

W2 = np.array([[0.5],
               [0.6]])

lr = 0.05

z1 = x @ W1
h = np.maximum(0, z1)          # ReLU
y_hat = h @ W2
loss = np.mean((y_hat - y) ** 2)

print("z1 =")
print(z1)

print("\nh =")
print(h)

print("\ny_hat =")
print(y_hat)

print("\nLoss before update =", loss)

dy = 2 * (y_hat - y)

dW2 = h.T @ dy

dh = dy @ W2.T

dz1 = dh * (z1 > 0)

dW1 = x.T @ dz1

print("\ndy =")
print(dy)

print("\ndW2 =")
print(dW2)

print("\ndh =")
print(dh)

print("\ndz1 =")
print(dz1)

print("\ndW1 =")
print(dW1)


W1 = W1 - lr * dW1
W2 = W2 - lr * dW2

z1_new = x @ W1
h_new = np.maximum(0, z1_new)
y_hat_new = h_new @ W2
loss_new = np.mean((y_hat_new - y) ** 2)

print("\nLoss after update =", loss_new)

z1 =
[[0.7 1. ]]

h =
[[0.7 1. ]]

y_hat =
[[0.95]]

Loss before update = 0.0025000000000000044

dy =
[[-0.1]]

dW2 =
[[-0.07]
 [-0.1 ]]

dh =
[[-0.05 -0.06]]

dz1 =
[[-0.05 -0.06]]

dW1 =
[[-0.05 -0.06]
 [-0.1  -0.12]]

Loss after update = 0.0007388203515624964


In [14]:
import sympy as sp

x, y = sp.symbols('x y')


f = x**4 + y**2

# Compute the Hessian matrix
H = sp.hessian(f, (x, y))

print("Function:")
print(f)

print("\nHessian Matrix:")
print(H)


x_val = 0          # Initial value
lr = 0.1           # Learning rate
steps = 20

for i in range(steps):
    grad = 2 * (x_val - 7)
    x_val = x_val - lr * grad

print("\nFinal x after Gradient Descent:", x_val)


Function:
x**4 + y**2

Hessian Matrix:
Matrix([[12*x**2, 0], [0, 2]])

Final x after Gradient Descent: 6.91929549467752
